import { Listing } from '../../types/listing/listing';

const defaultListing:Listing = {
    "id": "",
    "externalId" : "",
    "miqId" : "",
    "isDeleted": false,
    "propertyId": "",
    "pending": false,
    "state": "",
    "published": false,
    "editable": true,
    "propertyName": "",
    "propertyType": "",
    "propertyRecordName": "",
    "propertySubType": "",
    "propertyUseClass": "",
    "listingType": "",
    "street": "",
    "street2": "",
    "city": "",
    "stateOrProvince": "",
    "country": "",
    "postalCode": "",
    "energyRating": "",
    "buildingDescriptionSingle": "",
    "buildingDescription": [],
    "alternatePostalAddresses": [],
    "locationDescription": [],
    "locationDescriptionSingle": "",
    "status": "",
    "availableFrom": null,
    "syndicationFlag": false,
    "syndicationMarket": "",
    "website": "",
    "operator": "",
    "headlineSingle": "",
    "headline": [],
    "parkings": {
        "ratio": 0,
        "ratioPer": 0,
        "ratioPerUnit": "",
        "parkingDetails": []
    },
    "pointsOfInterests": [],
    "transportationTypes": [],
    "video": "",
    "walkThrough": "",
    "importedData": "",
    "aspects": [],
    "lng": 0,
    "lat": 0,
    "photos": [],
    "floorplans": [],
    "brochures": [],
    "highlights": [],
    "epcGraphs": null,
    "teams": [],
    "floors": null,
    "yearBuilt": null,
    "specifications": {
        "leaseType": "",
        "leaseRateType": "",
        "measure": "",
        "leaseTerm": "",
        "minSpace": 0,
        "maxSpace": 0,
        "totalSpace": 0,
        "minPrice": 0,
        "maxPrice": 0,
        "salePrice": 0,
        "contactBrokerForPrice": false,
        "showPriceWithUoM": false,
        "plusSalesTax": false,
        "includingSalesTax": false,
        "currencyCode": "USD"
    },
    "chargesAndModifiers": [],
    "propertySizes": [],
    "microMarkets" : [],
    "microMarket": "",
    "spaces": [],
    "spacesCount": 0,
    "contacts": [],
    "externalPublishUrl": "",
    "triggers": {
        addressChange: 0
    },
    "previewSearchApiEndPoint": "",
    "datasource" : {
        datasources: [],
        other: ""
    },
    "externalPreviewUrl": "", 
    "listingAssignment" : {
        assignedBy: "",
        assignmentFlag: false,
        assignedDate: new Date()
    },
    "dateCreated": new Date(),
    "dateUpdated": new Date(),
    "datePublished": new Date(),
    "dateListed": new Date()
}

export default defaultListing;